#undef HAVE_LIBSM
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef ENABLE_NLS

#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY

#undef HAVE_GETHOSTBYNAME_R_GLIBC
#undef HAVE_GETHOSTBYNAME_R_SOLARIS
#undef HAVE_GETHOSTBYNAME_R_HPUX
#undef HAVE_GETHOSTBYNAME_R_GLIB_MUTEX
#undef GPG_PATH
#undef PGP5_PATH
#undef PGP_PATH
#undef PGP_PROGRAM
#undef HAVE_XSS
#undef WITH_IPV6
#undef HAVE_XMMS
#undef MACOSX
#undef SOLARIS
#undef HAVE_STD_SSTREAM
#undef HAVE_SOCKLEN_T
